### ISSUE TITLE
In Workshop README.md, link of "Exercise 3: Machine Learning with Jupyter" is broken

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#145]
In Workshop README.md, link of "Exercise 3: Machine Learning with Jupyter" is broken

**Comment by scottdangelo** [comment]
Thanks. Can you be more specifiic? Which workshop README.md has the broken link, and which link is broken?
I suspect it is because I originally used a capital letter for `machine-learning-in-Jupyter-notebook`, which, for some reason, causes an issue with git and a case-sensitive/case-insensitive naming problem.
