### ISSUE TITLE
In README of "monitoring-models-with-openscale-gui", missing pictures

### ISSUE THREAD

**Issue by lee-zhg** [IBM/cloudpakfordata-telco-churn-workshop#146]
In README of "monitoring-models-with-openscale-gui", missing pictures,

In the Payload logging section, select the type of input. In our case, choose Categorical:

Choose model input type

In the Model details sections, select Manually configure monitors:

Choose model details
     ==> missing picture
In the Quality alert section, set the alert threshold to 70% and the sample size to 100:
     ==> missing picture
Set alert threshold and sample size
     ==> missing picture

**Comment by lee-zhg** [comment]
Re-Open Notebook

From your project page, go to Notebooks:
==> missing picture

**Comment by scottdangelo** [comment]
Thanks for the issue. Sorry, this module is a Work in Progress, and should not have been exposed. Parts of this are not fully tested, since it was ported from a workshop @jrtorres created using OpenScale on the IBM Cloud. Also, there are missing screen shots because of this.
We'll be taking on the work of updating this the week of April 20-24, and I hope to have these updates in by 4/24/20. Thanks again.

**Comment by jrtorres** [comment]
Closing this for now as we are developing this manual monitor configuration module in upstream.
